CREATE OR REPLACE TABLE POLICY_RAW (
    policy_number STRING,
    customer_id STRING,
    first_name STRING,
    last_name STRING,
    ssn STRING,
    email STRING,
    phone STRING,
    address STRING,
    city STRING,
    state STRING,
    zip STRING,
    policy_type STRING,
    effective_date STRING,
    expiration_date STRING,
    annual_premium STRING,
    payment_frequency STRING,
    renewal_flag STRING,
    policy_status STRING,
    marital_status STRING,
    agent_id STRING,
    agency_name STRING,
    agency_region STRING,
    load_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);